package com.ldnprod.timer.Services.Constants

const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
const val ACTION_SERVICE_PAUSE = "ACTION_SERVICE_STOP"
const val ACTION_SERVICE_STOP = "ACTION_SERVICE_CANCEL"
const val ACTION_SERVICE_NEXT = "ACTION_SERVICE_NEXT"

const val TRAINING_STATE = "TRAINING_STATE"
const val EXERCISE_ID = "EXERCISE_ID"

const val NOTIFICATION_CHANNEL_ID = "TRAINING_NOTIFICATION_CHANNEL_ID"
const val NOTIFICATION_CHANNEL_NAME = "TRAINING_NOTIFICATION_CHANNEL_NAME"
const val NOTIFICATION_ID = 10

const val CLICK_REQUEST_CODE = 100
const val STOP_REQUEST_CODE = 101
const val PAUSE_REQUEST_CODE = 102
const val RESUME_REQUEST_CODE = 103
const val NEXT_REQUEST_CODE = 104
